trigger:
- Dev

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Azure for Students Starter(efd75f38-514f-4465-892f-a99f48dbd70d)'
    scriptLocation: 'scriptPath'
    scriptPath: 
    addSpnToEnvironment: true
    useGlobalConfig: true
    workingDirectory: 'master'
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: 
    cd frontend
    npm install
    npm run build --output $(Build.ArtifactStagingDirectory)
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students Starter (efd75f38-514f-4465-892f-a99f48dbd70d)'
    appType: 'webAppLinux'
    WebAppName: 'NarfoFrontend'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students Starter (efd75f38-514f-4465-892f-a99f48dbd70d)'
    appType: 'webAppLinux'
    appName: 'NarfoFrontend'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
