# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Dev

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: 
    cd frontend
    npm install
    npm run build --output $(Build.ArtifactStagingDirectory)
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build  '

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: build

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
steps:
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build  '

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: build

pool:
  name: Hosted Ubuntu 1604
steps:
- task: NodeTool@0
  displayName: 'Use Node 11.x'
  inputs:
    versionSpec: 11.x
    checkLatest: true


